### ISSUE TITLE
Thermal/cruise state machine appears to have no state change from PossibleCruise back to Climb

### ISSUE THREAD

**Issue by roeles** [GliderGeek/OpenSoar#1]
I've distilled this state diagram from your code, please check if this is roughly correct.
![opensoar_thermal_detection](https://user-images.githubusercontent.com/1002026/32390805-23197038-c0d0-11e7-9a70-8c29ed173cf4.png)

I don't really see a state transition from PossibleCruise to Climb. You do check the transition to Cruise (when 1km has been cruised), but I see no place where `cruise` is set to `False`

**Comment by GliderGeek** [comment]
I find it difficult to interpret the diagram, but there is indeed a certain a-symmetry between cruise -> thermal and thermal -> cruise. the transition cruise -> thermal contains refinement.

from cruise -> thermal
- 225 degree continuous turn
- thermal start at first occurrence of >4deg/s or at start of turn

from thermal -> cruise
- absolute always <4deg/s, cruise distance > 1000m, average < 2 deg/s.

**Comment by GliderGeek** [comment]
Looking again at the diagram:
-  When in 'cruise' state, it is also in 'possible climb' state. If the bearing change sign changes (e.g. from cw to ccw), the 'possible `climb'` entry is updated and cumulative bearing change is reset.

In terms of arrows:
- PossibleClimb -> Climb takes place when ccw changes to cw and vice versa
- Climb -> PossibleClimb always takes place

**Comment by GliderGeek** [comment]
btw, to specifically answer the question on the cruise boolean:
it is set to False in line 62

**Comment by roeles** [comment]
I see, thanks!
