### ISSUE TITLE
Problem with keyhole sectors

### ISSUE THREAD

**Issue by jkretz** [GliderGeek/opensoar#45]
When analyzing a recent competition day, I realized that pysoar/opensoar has a problem with keyhole sectors. When flying through the 500m cylinder, a valid turnpoint is detected. Flying outside the cylinder but within the 90-degree sector results in an invalid turnpoint.

You may find an example in this competition day:
https://www.soaringspot.com/en_gb/altmarkpokal-2023-stendal/results/standard/task-6-on-2023-07-07/daily

**Comment by GliderGeek** [comment]
I fixed a problem with aat sectors in the latest release v1.1.0, is the problem you describe present in this version?

**Comment by jkretz** [comment]
It is related to racing tasks. I have been using pysoar 0.63 for Mac

**Comment by jkretz** [comment]
It is related to the recent AAT fix, but I haven't fully understood the changes yet

**Comment by jkretz** [comment]
It seems to be related to the `(180 - angle_wrt_orientation)` part that you recently added. Unfortunately, I don't fully understand why this was needed so I won't try to fix it

Here an image of the turnpoint in question if that helps (See flight of JK in the soaringspot URL of that day):
![grafik](https://github.com/GliderGeek/opensoar/assets/26433377/4219b13e-9aec-4223-89aa-5cabfa740a75)

**Comment by GliderGeek** [comment]
Thanks for the extra info. This part was difficult to understand, so i probably made a mistake. Luckily i created some geojson export functionality to help debugging last time

**Comment by GliderGeek** [comment]
good catch @jkretz. I'm addressing it here: https://github.com/GliderGeek/opensoar/pull/46
